=== adriennickson/java-xml-parser-ionis-stm/src/main/resources/static/xml/carte.dtd
<!ELEMENT carte (recto,verso) >
<!ELEMENT recto (photo,nom,prenom,sexe,naissance,taille,signature) >
<!ELEMENT verso (adresse,date,par) >

<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT taille (#PCDATA) >
<!ELEMENT adresse (#PCDATA) >
<!ELEMENT par (#PCDATA) >
<!ELEMENT photo EMPTY >
<!ELEMENT sexe EMPTY >
<!ELEMENT naissance EMPTY >
<!ELEMENT signature EMPTY >
<!ELEMENT date EMPTY >

<!ATTLIST carte numero CDATA #REQUIRED >
<!ATTLIST sexe valeur CDATA #REQUIRED >
<!ATTLIST naissance date CDATA #REQUIRED
                    lieu CDATA #REQUIRED >
<!ATTLIST date delivrance CDATA #REQUIRED
                expiration CDATA #REQUIRED >
<!ATTLIST photo src CDATA #IMPLIED >
<!ATTLIST signature src CDATA #IMPLIED >

=== adriennickson/java-xml-parser-ionis-stm/src/main/resources/static/xml/carte01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carte SYSTEM "carte.dtd">
<carte numero="880692310286">
    <recto>
        <photo src="img_avatar01.png"/>
        <nom>MAXIME XYZ</nom>
        <prenom>LEDUC XYZ</prenom>
        <sexe valeur="M"/>
        <naissance date="1963-12-06" lieu="Dijon"/>
        <taille>1M70</taille>
        <signature src="signature01.png"/>
    </recto>
    <verso>
        <adresse>104 RUE DES FLEURS 92100 BOULOGNE BILLANCOURT (92)</adresse>
        <date delivrance="1998-06-21" expiration="1988-06-22"/>
        <par>SOUS-PREFECTURE DE BOULOGNE BILLANCOURT (92)</par>
    </verso>
    <nationalite>
        <FRA fullname="FRANCAISE"/>
    </nationalite>
</carte>

=== adriennickson/java-xml-parser-ionis-stm/src/main/resources/static/xml/carte02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carte SYSTEM "carte.dtd">
<carte numero="880692310285">
    <recto>
        <photo src="img_avatar02.png"/>
        <nom>TOMAS</nom>
        <prenom>CORINE</prenom>
        <sexe valeur="F"/>
        <naissance date="1965-12-06" lieu="PARIS 1ER (75)"/>
        <taille>1M70</taille>
        <signature src="signature02.png"/>
    </recto>
    <verso>
        <adresse>104 RUE DES FLEURS 92100 BOULOGNE BILLANCOURT (92)</adresse>
        <date delivrance="1998-06-21" expiration="1988-06-22"/>
        <par>SOUS-PREFECTURE DE BOULOGNE BILLANCOURT (92)</par>
    </verso>
    <nationalite>
        <GER fullname="ALLEMANDE">
            <puce/>
        </GER>
    </nationalite>
</carte>
